global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  # Uncomment if you use Postgres for tokenlist fallback
  - job_name: 'database'
    static_configs:
      - targets: ['database:5432']

  - job_name: 'custom_metrics'
    static_configs:
      - targets: ['custom_metrics:8080']