
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: wallydb
      POSTGRES_USER: wallyuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"